- name: Get list of existing Kafka topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --list
  register: existing_ingestion_kafka_topics
  tags:
    - ingestion-kafka

- name: create topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --create --topic "{{env}}.{{ item.name}}" --partitions {{ item.num_of_partitions}} --replication-factor {{ item.replication_factor}}
  with_items: "{{ingestion_kafka_topics}}"
  ignore_errors: true
  when: kafka_id == "1" and "{{env}}.{{ item.name }}" not in existing_ingestion_kafka_topics.stdout_lines
  tags:
    - ingestion-kafka

- name: override retention time
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --config retention.ms={{ item.retention_time }}
  with_items: "{{ingestion_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.retention_time is defined
  tags:
    - ingestion-kafka

- name: Get list of existing Kafka topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --list
  register: existing_processing_kafka_topics
  tags:
    - processing-kafka

- name: create topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --create --topic "{{env}}.{{ item.name}}" --partitions {{ item.num_of_partitions}} --replication-factor {{ item.replication_factor}}
  ignore_errors: true
  when: kafka_id == "1" and "{{env}}.{{ item.name }}" not in existing_processing_kafka_topics.stdout_lines
  with_items: "{{processing_kafka_topics}}"
  tags:
    - processing-kafka

- name: override retention time
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --config retention.ms={{ item.retention_time }}
  with_items: "{{processing_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.retention_time is defined
  tags:
    - processing-kafka

- name: overriding default partition size
  shell: "/opt/kafka/bin/kafka-topics.sh  --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{item}} --config max.message.bytes={{kafka_partition_override_size}}"
  with_items:
    - "{{env}}.telemetry.ingest"
    - "{{env}}.telemetry.extractor.failed"

- name: overriding data pipeline downstream topic size
  shell: "/opt/kafka/bin/kafka-topics.sh  --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{item}} --config max.message.bytes={{dp_downstream_kafka_max_message_bytes}}"
  with_items:
    - "{{env}}.druid.events.error"
    - "{{env}}.druid.events.log"
    - "{{env}}.druid.events.summary"
    - "{{env}}.druid.events.telemetry"
    - "{{env}}.telemetry.assess.raw"
    - "{{env}}.telemetry.audit"
    - "{{env}}.telemetry.denorm"
    - "{{env}}.telemetry.duplicate"
    - "{{env}}.telemetry.error"
    - "{{env}}.telemetry.extractor.duplicate"
    - "{{env}}.telemetry.extractor.failed"
    - "{{env}}.telemetry.failed"
    - "{{env}}.telemetry.ingest"
    - "{{env}}.telemetry.raw"
    - "{{env}}.telemetry.unique"
    - "{{env}}.telemetry.unique.latest"
    - "{{env}}.telemetry.unique.primary"
    - "{{env}}.telemetry.unique.secondary"
